---
- hosts: aws_ec2
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Install Java 8 CentOS
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Install httpd service
    yum:
      name: httpd
      state: present
  - name: Start httpd service
    service:
      name: httpd
      state: restarted
