---
- hosts: aws_ec2
  remote_user: ec2-user
  gather_facts: yes
  become: yes
  vars:
    - version: tomcat-10.0.18
  tasks:
    - name: install java
      yum:
        name: java
        state: latest
    - name: download pkg
      get_url:
         url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.18/bin/apache-tomcat-10.0.18.tar.gz
         dest: /usr/local
         validate_certs: no
    - name: extracting tomcat file
      unarchive:
         src: /usr/local/apache-tomcat-10.0.18.tar.gz
         dest: /usr/local
         remote_src: yes
    - name: start tomcat service
      shell: nohup /usr/local/apache-tomcat-10.0.18/bin/startup.sh
